import type { Persona, KnowledgeDomain } from '../types';

export const API_BASE_URL = import.meta.env.VITE_API_URL || 'http://localhost:8000';

export const PERSONAS: Persona[] = [
  { id: 'new_joiner', name: 'New Joiner', icon: '🌱', description: 'Recently joined employee learning the ropes' },
  { id: 'operations_analyst', name: 'Operations Analyst', icon: '📊', description: 'Experienced analyst handling day-to-day operations' },
  { id: 'manager', name: 'Manager', icon: '👔', description: 'Team manager overseeing operations and risk' },
  { id: 'director', name: 'Director', icon: '🎯', description: 'Senior leader with strategic oversight' },
  { id: 'automation_team', name: 'Automation Team', icon: '⚙️', description: 'Technology specialist implementing automations' },
  { id: 'internal_auditor', name: 'Internal Auditor', icon: '🔎', description: 'Conducting internal assurance reviews' },
  { id: 'external_auditor', name: 'External Auditor', icon: '📋', description: 'Independent external review specialist' },
  { id: 'compliance_officer', name: 'Compliance Officer', icon: '✅', description: 'Managing regulatory compliance obligations' },
  { id: 'risk_owner', name: 'Risk Owner', icon: '🛡️', description: 'Accountable for identifying and managing risks' },
  { id: 'process_owner', name: 'Process Owner', icon: '🔄', description: 'Responsible for end-to-end process management' },
];

export const KNOWLEDGE_DOMAINS: KnowledgeDomain[] = [
  {
    id: 'operations',
    name: 'Operations & Service Management',
    icon: '🏭',
    description: 'SOPs, incident management, SLA requirements, escalation procedures, and operational excellence frameworks.',
    documentCount: 12,
    color: '#0052cc',
    keywords: ['SLA', 'incidents', 'escalation', 'MTTR', 'KPIs', 'ServiceNow'],
    insights: ['Customer First always', 'P1 resolution within 4 hours', 'Document all escalations', 'Root cause prevents recurrence'],
  },
  {
    id: 'automation',
    name: 'Automation & Innovation',
    icon: '🤖',
    description: 'RPA governance, automation lifecycle, business ownership, testing requirements, and monitoring standards.',
    documentCount: 8,
    color: '#7c3aed',
    keywords: ['RPA', 'automation', 'governance', 'testing', 'monitoring', 'fallback'],
    insights: ['Every automation needs a Business Owner', 'Test before deploy', 'Monitor in production', 'Always have a fallback'],
  },
  {
    id: 'risk',
    name: 'Risk Management',
    icon: '⚠️',
    description: 'Enterprise risk framework, RCSA, risk appetite, three lines of defense, and escalation protocols.',
    documentCount: 15,
    color: '#dc2626',
    keywords: ['RCSA', 'risk register', 'KRI', 'appetite', 'escalation', 'three lines'],
    insights: ['Identify risks early', 'Escalate High risks within 5 days', 'Monitor KRIs weekly', 'Risk ownership drives accountability'],
  },
  {
    id: 'controls',
    name: 'Controls Framework',
    icon: '🛡️',
    description: 'Control design, COSO alignment, testing frequencies, evidence requirements, and remediation tracking.',
    documentCount: 10,
    color: '#059669',
    keywords: ['COSO', 'SOX', 'control testing', 'deficiency', 'remediation', 'evidence'],
    insights: ['Preventive controls stop errors', 'Evidence retained 7 years', 'Material weaknesses need immediate action', 'Test regularly'],
  },
  {
    id: 'audit',
    name: 'Audit & Assurance',
    icon: '🔍',
    description: 'Internal audit methodology, risk-based planning, fieldwork standards, findings management, and follow-up.',
    documentCount: 11,
    color: '#0891b2',
    keywords: ['audit plan', 'fieldwork', 'findings', 'evidence', 'remediation', 'assurance'],
    insights: ['Evidence must be sufficient and appropriate', 'Critical findings need immediate action', 'Follow-up until closed', 'Independence is paramount'],
  },
  {
    id: 'compliance',
    name: 'Compliance & Data Protection',
    icon: '📋',
    description: 'GDPR obligations, MiFID II, Basel III, PSD2, compliance monitoring, and regulatory breach management.',
    documentCount: 14,
    color: '#7c3aed',
    keywords: ['GDPR', 'MiFID II', 'Basel III', 'PSD2', 'compliance monitoring', 'regulatory reporting'],
    insights: ['Compliance is everyone\'s responsibility', 'Report breaches within 24 hours', 'Data subject rights within 30 days', 'Train annually'],
  },
  {
    id: 'governance',
    name: 'Governance & Policy Management',
    icon: '⚖️',
    description: 'Policy hierarchy, lifecycle management, governance committees, annual certification, and exception processes.',
    documentCount: 9,
    color: '#d97706',
    keywords: ['policy', 'governance', 'committees', 'certification', 'approval', 'exception'],
    insights: ['Every policy needs an owner', 'Annual certification is mandatory', 'Exceptions need Risk sign-off', 'Review annually'],
  },
  {
    id: 'euda',
    name: 'EUDA & Application Governance',
    icon: '💻',
    description: 'EUDA inventory, classification criteria, ownership requirements, risk assessment, and annual review.',
    documentCount: 7,
    color: '#0e7490',
    keywords: ['EUDA', 'spreadsheet', 'inventory', 'classification', 'ownership', 'critical'],
    insights: ['Register EUDAs within 30 days', 'Critical EUDAs need annual review', 'Always have a Business Owner', 'Document data sources'],
  },
  {
    id: 'learning',
    name: 'Learning & Onboarding',
    icon: '📚',
    description: 'Onboarding frameworks, mandatory training, competency development, and continuous learning programs.',
    documentCount: 6,
    color: '#16a34a',
    keywords: ['onboarding', 'training', 'mandatory', 'competency', 'probation', 'dblearn+'],
    insights: ['Complete mandatory training in week 1', '40 learning hours per year', 'Mentoring accelerates growth', 'Monthly check-ins during probation'],
  },
  {
    id: 'hr',
    name: 'HR Management',
    icon: '👥',
    description: 'HR policies, performance management, flexible working, benefits, wellbeing, and employee relations.',
    documentCount: 8,
    color: '#db2777',
    keywords: ['annual leave', 'remote working', 'performance', 'benefits', 'wellbeing', 'disciplinary'],
    insights: ['Core hours 10am-3pm', 'Up to 40% remote working', 'EAP available for wellbeing', 'Zero tolerance for discrimination'],
  },
];

export const TOP_10_TOPICS = [
  { topic: 'Audit Readiness Actions', domain: 'audit', icon: '🔍' },
  { topic: 'Operational Risks', domain: 'risk', icon: '⚠️' },
  { topic: 'Compliance Checks', domain: 'compliance', icon: '✅' },
  { topic: 'Controls Best Practices', domain: 'controls', icon: '🛡️' },
  { topic: 'Governance Practices', domain: 'governance', icon: '⚖️' },
  { topic: 'Automation Ideas', domain: 'automation', icon: '🤖' },
  { topic: 'Onboarding Tips for New Joiners', domain: 'learning', icon: '🌱' },
  { topic: 'EUDA Management Actions', domain: 'euda', icon: '💻' },
  { topic: 'Operational Best Practices', domain: 'operations', icon: '🏭' },
  { topic: 'Risk Escalation Actions', domain: 'risk', icon: '🚨' },
];

export const BUSINESS_INSIGHTS = [
  { title: 'Ownership Drives Accountability', description: 'Clear ownership ensures every process, risk, and control has an accountable party.', icon: '👤' },
  { title: 'Risk Should Be Identified Early', description: 'Proactive risk identification prevents escalation and reduces impact.', icon: '🔭' },
  { title: 'Effective Controls Reduce Failures', description: 'Well-designed controls prevent errors before they occur.', icon: '🛡️' },
  { title: 'Evidence Matters', description: 'Documentation and audit trails are the foundation of assurance.', icon: '📋' },
  { title: 'Timely Escalation Prevents Issues', description: 'Escalating at the right time stops small problems becoming large ones.', icon: '⬆️' },
  { title: 'Compliance Is Everyone\'s Responsibility', description: 'A strong compliance culture starts with individual accountability.', icon: '✅' },
  { title: 'Automation Must Be Governed', description: 'Without proper governance, automation creates new risks.', icon: '⚙️' },
  { title: 'Continuous Learning Builds Resilience', description: 'Learning agility is a competitive advantage in a changing regulatory environment.', icon: '📚' },
  { title: 'Data Is A Business Asset', description: 'Data quality, protection, and governance are strategic priorities.', icon: '💾' },
  { title: 'Continuous Improvement Creates Value', description: 'Regular review and improvement of processes creates lasting business value.', icon: '📈' },
];

export const DEMO_CREDENTIALS = [
  { email: 'admin@deutschebank.com', password: 'demo123', role: 'Admin', name: 'Admin User' },
  { email: 'analyst@deutschebank.com', password: 'demo123', role: 'Operations Analyst', name: 'John Smith' },
  { email: 'manager@deutschebank.com', password: 'demo123', role: 'Manager', name: 'Sarah Johnson' },
  { email: 'auditor@deutschebank.com', password: 'demo123', role: 'Internal Auditor', name: 'Michael Chen' },
  { email: 'compliance@deutschebank.com', password: 'demo123', role: 'Compliance Officer', name: 'Emma Wilson' },
  { email: 'demo@demo.com', password: 'demo', role: 'Demo User', name: 'Demo User' },
];
